kind: Service
apiVersion: v1
metadata:
  name: {{ include "launcher.fullname" . }}
  labels:
    {{- include "launcher.labels" . | nindent 4 }}
spec:
  ports:
    - name: '8080'
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "launcher.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
