{{- if eq .Values.auth "oauth" -}}
kind: OAuthClient
apiVersion: oauth.openshift.io/v1
metadata:
  name: {{ .Values.oauth.clientId | quote }}
  labels:
    {{- include "launcher.labels" . | nindent 4 }}
secret: launcher-oauth-client-secret
redirectURIs:
  - {{ .Values.oauth.redirectUrl | quote }}
grantMethod: prompt
{{- end -}}
