kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "launcher.fullname" . }}
  labels:
    {{- include "launcher.labels" . | nindent 4 }}
data:
  launcher.git.provider: {{ .Values.gitProvider | quote }}
  launcher.frontend.sentry.dsn: {{ .Values.frontend.sentryDsn | quote }}
  launcher.frontend.targetenvironment.skip: {{ .Values.frontend.targetEnvironmentSkip | quote }}
  launcher.backend.url: /launch/api
  launcher.backend.catalog.git.repository: {{ .Values.backend.catalog.git.repository | quote }}
  launcher.backend.catalog.git.ref: {{ .Values.backend.catalog.git.ref | quote }}
  launcher.backend.catalog.prefetch: {{ .Values.backend.catalog.prefetch | quote }}
  launcher.backend.catalog.filter: {{ .Values.backend.catalog.filter | quote }}
  launcher.backend.catalog.reindex.token: {{ .Values.backend.catalog.reindexToken | quote }}
  launcher.backend.git.repository.description: {{ .Values.backend.gitRepositoryDescription | quote }}
  launcher.backend.documentation.reload.token: {{ .Values.backend.documentationReloadToken | quote }}
  launcher.backend.sentry.dsn: {{ .Values.backend.sentryDsn | quote }}
  launcher.creator.enabled: {{ .Values.creator.enabled | quote }}
  launcher.creator.url: {{ .Values.creator.url | quote }}
  launcher.creator.sentry.dsn: {{ .Values.creator.sentryDsn | quote }}
  launcher.welcome.image.name: {{ .Values.welcome.image.name | quote }}
  launcher.welcome.image.tag: {{ .Values.welcome.image.tag | quote }}
  launcher.missioncontrol.openshift.api.url: {{ .Values.openshift.apiUrl | quote }}
  launcher.missioncontrol.openshift.console.url: {{ .Values.openshift.consoleUrl | quote }}
  launcher.missioncontrol.openshift.impersonate.user: {{ .Values.openshift.impersonateUser | quote }}
  launcher.missioncontrol.gitlab.url: {{ .Values.legacyGitProvider.gitlab.url | quote }}
  launcher.missioncontrol.gitea.url: {{ .Values.legacyGitProvider.gitea.url | quote }}
  {{- if eq .Values.auth "keycloak" }}
  launcher.keycloak.url: {{ .Values.keycloak.url | quote }}
  launcher.keycloak.realm: {{ .Values.keycloak.realm | quote }}
  launcher.keycloak.client.id: {{ .Values.keycloak.clientId | quote }}
  {{- else }}
  launcher.keycloak.url: ""
  launcher.keycloak.realm: ""
  launcher.keycloak.client.id: ""
  {{- end }}
  {{- if eq .Values.auth "oauth" }}
  launcher.oauth.openshift.url: {{ .Values.oauth.openshiftUrl | quote }}
  launcher.oauth.openshift.clientId: {{ .Values.oauth.clientId | quote }}
  {{- else }}
  launcher.oauth.openshift.url: ""
  launcher.oauth.openshift.clientId: ""
  {{- end }}
  launcher.tracker.segment.token: {{ .Values.trackerToken | quote }}
  launcher.filter.runtime: {{ .Values.filter.runtime | quote }}
  launcher.filter.version: {{ .Values.filter.version | quote }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "launcher.fullname" . }}-clusters
  labels:
    {{- include "launcher.labels" . | nindent 4 }}
data:
  openshift-clusters.yaml: |-
    {{- toYaml .Values.keycloak.clusters | nindent 4 }}
  git-providers.yaml: |-
  {{- range $key, $value := .Values.gitProviders }}
    - id: {{ $key }}
      {{- toYaml $value | nindent 6 }}
  {{- end}}
