apiVersion: v1
kind: Secret
metadata:
  name: {{ include "launcher.fullname" . }}
  labels:
    {{- include "launcher.labels" . | nindent 4 }}
stringData:
  launcher.missioncontrol.openshift.clusters.subscription.token: {{ .Values.openshift.clusterSubscriptionToken | quote }}
  {{- if eq .Values.auth "direct" }}
  launcher.missioncontrol.openshift.username: {{ .Values.openshift.username | quote }}
  launcher.missioncontrol.openshift.password: {{ .Values.openshift.password | quote }}
  launcher.missioncontrol.openshift.token: {{ .Values.openshift.token | quote }}
  launcher.missioncontrol.github.token: {{ .Values.legacyGitProvider.github.token | quote }}
  launcher.missioncontrol.gitlab.token: {{ .Values.legacyGitProvider.gitlab.token | quote }}
  launcher.missioncontrol.bitbucket.username: {{ .Values.legacyGitProvider.bitbucket.username | quote }}
  launcher.missioncontrol.bitbucket.password: {{ .Values.legacyGitProvider.bitbucket.password | quote }}
  launcher.missioncontrol.gitea.username: {{ .Values.legacyGitProvider.gitea.username | quote }}
  launcher.missioncontrol.gitea.token: {{ .Values.legacyGitProvider.gitea.token | quote }}
  {{- else }}
  launcher.missioncontrol.openshift.username: ""
  launcher.missioncontrol.openshift.password: ""
  launcher.missioncontrol.openshift.token: ""
  launcher.missioncontrol.github.token: ""
  launcher.missioncontrol.gitlab.token: ""
  launcher.missioncontrol.bitbucket.username: ""
  launcher.missioncontrol.bitbucket.password: ""
  launcher.missioncontrol.gitea.username: ""
  launcher.missioncontrol.gitea.token: ""
  {{- end }}
